export{
    GET_SMURFS_REQUEST,
    GET_SMURFS_SUCCESS,
    GET_SMURFS_FAILURE,
    MAKE_THE_SMURF_REQUEST,
    MAKE_THE_SMURF_SUCCESS,
    MAKE_THE_SMURF_FAILURE,
    getSmurfs,
    makeSmurf
} from './actions';